/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Admin, Employee } from "./types";

export const MOCK_ADMINS: Admin[] = [
  { email: "ashutosh@teachmint.com", password: "ashu123", name: "Ashutosh Unhale", role: "admin" },
  { email: "hr@teachmint.com", password: "hr123", name: "HR", role: "admin" },
  { email: "sanju.ts@teachmint.com", password: "admin123", name: "Sanju T", role: "admin" },
  { email: "preeta@teachmint.com", password: "admin123", name: "Preeta Saxena", role: "admin" },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "EMP001",
    email: "ashutosh@teachmint.com",
    mobile: "9876543210",
    password: "emp123",
    name: "Ashutosh Unhale",
    department: "CEO's Office",
    designation: "Senior Director",
    joinDate: "2020-09-15",
    grantDate: "2020-09-15",
    grants: [
      {
        id: "GR001",
        grantDate: "2020-09-15",
        totalShares: 2000,
        vestedShares: 1500,
        exercisedShares: 500,
        strikePrice: 85,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
      {
        id: "GR002",
        grantDate: "2022-01-01",
        totalShares: 1000,
        vestedShares: 375,
        exercisedShares: 0,
        strikePrice: 120,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
    ],
    transactions: [
      { date: "2022-10-05", type: "Exercise", shares: 500, price: 85, fmv: 150, gain: 32500 },
      { date: "2023-04-12", type: "Vesting", shares: 250, price: null, fmv: 170, gain: null },
    ],
  },
  {
    id: "EMP002",
    email: "neeraj@teachmint.com",
    mobile: "9123456780",
    password: "emp123",
    name: "Neeraj Kumar",
    department: "Commercial",
    designation: "Assistant Manager",
    joinDate: "2021-06-01",
    grantDate: "2021-12-01",
    grants: [
      {
        id: "GR003",
        grantDate: "2021-12-01",
        totalShares: 1500,
        vestedShares: 843,
        exercisedShares: 0,
        strikePrice: 100,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
    ],
    transactions: [
      { date: "2022-12-01", type: "Vesting", shares: 375, price: null, fmv: 155, gain: null },
    ],
  },
  {
    id: "EMP003",
    email: "vinay@teachmint.com",
    mobile: "9988776655",
    password: "emp123",
    name: "Vinay Bansal",
    department: "Commercial",
    designation: "Senior Associate",
    joinDate: "2019-11-20",
    grantDate: "2020-05-20",
    grants: [
      {
        id: "GR004",
        grantDate: "2020-05-20",
        totalShares: 3000,
        vestedShares: 3000,
        exercisedShares: 1500,
        strikePrice: 70,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Fully Vested",
      },
    ],
    transactions: [
      { date: "2021-06-01", type: "Exercise", shares: 750, price: 70, fmv: 120, gain: 37500 },
      { date: "2022-09-14", type: "Exercise", shares: 750, price: 70, fmv: 175, gain: 78750 },
    ],
  },
  {
    id: "EMP004",
    email: "chinnappa@teachmint.com",
    mobile: "9001122334",
    password: "emp123",
    name: "Chinnappa C M",
    department: "Finance",
    designation: "Manager",
    joinDate: "2022-02-14",
    grantDate: "2022-08-14",
    grants: [
      {
        id: "GR005",
        grantDate: "2022-08-14",
        totalShares: 2500,
        vestedShares: 468,
        exercisedShares: 0,
        strikePrice: 140,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
    ],
    transactions: [],
  },
  {
    id: "TE-1259",
    email: "sanju.ts@teachmint.com",
    mobile: "9999999991",
    password: "emp1234",
    name: "Sanju T",
    department: "Business Finance",
    designation: "Manager",
    joinDate: "2025-04-01",
    grantDate: "2025-04-01",
    cliffType: "Annually",
    grants: [
      {
        id: "GR-TM-2025-1259",
        grantDate: "2025-04-01",
        totalShares: 2.11,
        vestedShares: 0,
        exercisedShares: 0,
        strikePrice: 1,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
    ],
    transactions: [],
  },
  {
    id: "EMP006",
    email: "preeta@teachmint.com",
    mobile: "9999999992",
    password: "emp065",
    name: "Preeta Saxena",
    department: "Human Resources",
    designation: "Associate Vice President - Human Resources & CISO",
    joinDate: "2024-05-17",
    grantDate: "2024-05-17",
    grants: [
      {
        id: "GR-TM-2024-002",
        grantDate: "2024-05-17",
        totalShares: 0.64,
        vestedShares: 0,
        exercisedShares: 0,
        strikePrice: 1,
        currentFMV: 210,
        vestingSchedule: "4yr/1yr cliff (Quarterly)",
        status: "Active",
      },
    ],
    transactions: [],
  },
];
